### ISSUE TITLE
Create a offering, product plan, api/sdk draft for Silvi

### ISSUE THREAD

**Issue by ronerlih** [AstralProtocol/astralprotocol#101]
**Tasks**
- [ ] ...

**Please Note the fields to the right_**
- [ ] I've selected a milestone or created one.
- [ ] I've set a suggested priority.
- [ ] I've set an effor estimation (numerical).
