### ISSUE TITLE
Complete Kernel Pitch

### ISSUE THREAD

**Issue by gattmen** [AstralProtocol/astralprotocol#29]
**Tasks**
- Sign up (Danny)
- Develop Pitch materials (Gattman)
- Create MVP / lite pilot to demonstrate astral's functionality (ron)
- Conduct Dry Run (Danny & Ron)
- Pitch (Danny & Ron) 

**Please Note the fields to the right_**
- [ ] I've selected a milestone or created one.
- [ ] I've set a suggested priority.
- [ ] I've set an effor estimation (numerical).
