### ISSUE TITLE
[CORE SETUP - TASK] setup gitbook subdomain

### ISSUE THREAD

**Issue by ronerlih** [AstralProtocol/astralprotocol#34]
**Tasks**
- [ ] reinstate docs.astral.global - solve DNS issue, 
(atm using the gitbook published link: https://astral-protocol.gitbook.io/astral/ 

**Please Note the fields to the right_**
- [ ] I've selected a milestone or created one.
- [ ] I've set a suggested priority.
- [ ] I've set an effor estimation (numerical).
