### ISSUE TITLE
[CORE SETUP - TASK] Update "new issue" template, add PR template

### ISSUE THREAD

**Issue by ronerlih** [AstralProtocol/astralprotocol#47]
**Tasks**
- [ ] ...

**Please Note the fields to the right_**
- [ ] I've selected a milestone or created one.
- [ ] I've set a suggested priority.
- [ ] I've set an effor estimation (numerical).
