### ISSUE TITLE
[FEAT] Implement EAS accessory contract

### ISSUE THREAD

**Issue by ronerlih** [AstralProtocol/astralprotocol#57]
**Tasks**
- [ ] Spike a plan (schema & flow-resolver) for EAS implementation
- [ ] Schema contract
- [ ] resolver contract (OPT, might be a separate ticket)

**Please Note the fields to the right_**
- [x] I've selected a milestone or created one.
- [ ] I've set a suggested priority.
- [ ] I've set an effor estimation (numerical).
