### ISSUE TITLE
Move coords from strings to numbers, TBD

### ISSUE THREAD

**Issue by ronerlih** [AstralProtocol/astralprotocol#61]
**Tasks**
- [ ] ...

**Please Note the fields to the right_**
- [ ] I've selected a milestone or created one.
- [ ] I've set a suggested priority.
- [ ] I've set an effor estimation (numerical).
