### ISSUE TITLE
[CHORE] Phrase issues from EAS product plan.

### ISSUE THREAD

**Issue by ronerlih** [AstralProtocol/astralprotocol#76]
## 📘 Story (required for top level issues pls)

As a DEV, I'd like to pick up issues for EAS MVP, so that i'll be able to focus on the work at hand, have context to our work, and monitor progress.

## 💬 Description
Use the [figma plan](https://www.figma.com/file/0y3zxXCoTMLKO8cp3Ymf7T/How-Astral-Works-%E2%80%94%C2%A0Flow-Diagram?type=whiteboard&node-id=117-1306&t=7hH3GR1PJTaABzJS-0) to extract issues for EAS MVP.

## 🗞️ Context
EAS MVP.

## 🏗️ TO-DO (tasks or sub-issues)
- [ ] Phrase issues.
- [ ] Build issues into hierarchies. 

## ✅ Acceptance criteria

- [ ] Clear issue items (by template)
- [ ] Creat sub-issues nested under parent issues.

## 📷 Screenshots
![Screen Shot 2024-04-30 at 15 43 22](https://github.com/AstralProtocol/astralprotocol/assets/7093389/47f41512-0a37-4d4f-8e45-97ec4785090e)

## 📓 Notes
-
