### ISSUE TITLE
Deploy EAS MVP on Vercel

### ISSUE THREAD

**Issue by ronerlih** [AstralProtocol/astralprotocol#77]
## 📘 Story (required for top level issues pls)

As a DEV, I'd like to test my work remotely, so that debug and share it for input.

## 💬 Description
Deploy EAS MVP (folder: `eas-mvp-checkin`) to [vercel project](https://vercel.com/new/rons-projects-d1ed21e8)

## 🗞️ Context
EAS MVP

## 🏗️ TO-DO (tasks or sub-issues)

- [ ] remove git subfolder.
- [ ] Set up pipeline for `eas-mvp-checkin` folder.
- [ ] use `engineering@astral.global` account.
- [ ] document on readme and notion (vercel deployment).

## ✅ Acceptance criteria
- [ ] Working pipeline.
- [ ] Readme doc.
- [ ] Notion Vercel documentation.
