### ISSUE TITLE
Deploy EAS schema on EAS

### ISSUE THREAD

**Issue by ronerlih** [AstralProtocol/astralprotocol#78]
## 💬 Description
Add EAS schema (basic, location field only at this point -mvp).

## 🗞️ Context
EAS MVP.

## 🏗️ TO-DO (tasks or sub-issues)
- [x] Design schema — [Notion](https://www.notion.so/astral-protocol/EAS-Schema-Design-v0-0-01883ae70e13431b879b4e8e1a06e557?pvs=4)
     - [x]  confirm with @ronerlih 
- [x] Add schema on [EAS schema builder](https://docs.attest.org/docs/tutorials/create-a-schema)
- [ ] Doc on readme.

## ✅ Acceptance criteria

- [x] EAS schema with a location field.
- [x] Chain - sepolia-op

## 📷 Screenshots
![Screen Shot 2024-04-30 at 18 16 39](https://github.com/AstralProtocol/astralprotocol/assets/7093389/b216a0f1-5ae7-43a0-bbeb-e3f8a73df021)

## 📓 Notes
[Schema #303](https://optimism-sepolia.easscan.org/schema/view/0x7408b55e86f7e249787fb617ddac48450fb7512609eb7c95fe6f97f49914f51e) on OP Sepolia, UID 0x7408b55e86f7e249787fb617ddac48450fb7512609eb7c95fe6f97f49914f51e

**Comment by johnx25bd** [comment]
Deployed [Schema #303](https://optimism-sepolia.easscan.org/schema/view/0x7408b55e86f7e249787fb617ddac48450fb7512609eb7c95fe6f97f49914f51e) on OP Sepolia, UID 0x7408b55e86f7e249787fb617ddac48450fb7512609eb7c95fe6f97f49914f51e
