### ISSUE TITLE
Add top level HEADER component, with a nested wallet component.

### ISSUE THREAD

**Issue by ronerlih** [AstralProtocol/astralprotocol#79]
## 📘 Story (required for top level issues pls)
As a check-in user, I'd like to connect my wallet on any chain, so that sign my transactions.

## 💬 Description
Add a (top level, always visible) header component, with a scoffold-eth"Account" component.

## 🗞️ Context
EAS MVP

## 🏗️ TO-DO (tasks or sub-issues)
- [ ] Add top level full width header component.
- [ ] Add a child "Account "component.
- [ ] Test on multiple chains. (Sepolia, Sepolia-arb as a priority).

## ✅ Acceptance criteria
- [ ] Header appears on all views.
- [ ] User's wallet connects on multiple wallets (metamask as a priority) and multiple chains (Sepolia, Sepolia-arb)

## 📷 Screenshots
![Screen Shot 2024-04-30 at 18 20 40](https://github.com/AstralProtocol/astralprotocol/assets/7093389/4266fd44-2876-4b85-a59f-2f249252def8)
