### ISSUE TITLE
Display form according to schema.

### ISSUE THREAD

**Issue by ronerlih** [AstralProtocol/astralprotocol#85]
## 💬 Description
Display attestation form (according to schema #78).

## 🗞️ Context
EAS MVP. on submit will call `attest` method on `EAS.sol`. 
#84 

## 🏗️ TO-DO (tasks or sub-issues)
- [ ] Reference EAS schema to create and populate form fields.
- [ ] Populate coordinate field with prop (from map component).
- [ ] Populate address field with Account component.

## ✅ Acceptance criteria
- Display form UI according to schema.
- Populate Coordinate and Address fields.

## 📷 Screenshots
![Screen Shot 2024-04-30 at 19 39 55](https://github.com/AstralProtocol/astralprotocol/assets/7093389/b2bc32e1-c908-47f9-b8af-8a8c8a5841b2)
