### ISSUE TITLE
Call attest method on submit.

### ISSUE THREAD

**Issue by ronerlih** [AstralProtocol/astralprotocol#86]
## 💬 Description
On form submit, call `EAS.sol` "attest" method with form data.

## 🗞️ Context
EAS MVP.
#84 

## 🏗️ TO-DO (tasks or sub-issues)
- [ ] Format the call data from the form and call EAS.sol. 
- [ ] Call `EAS.sol` "Attest" method.
- [ ] On wallet resolution, use tx hash to navigate to astral.global/tx/<tx hash> (tx won't be available yet though).

## ✅ Acceptance criteria
- Successful attestation (after user wallet tx prompt).
- User is directed to the `astral.global/tx/<tx hash>`.

## 📷 Screenshots
![Screen Shot 2024-04-30 at 19 39 55](https://github.com/AstralProtocol/astralprotocol/assets/7093389/b2bc32e1-c908-47f9-b8af-8a8c8a5841b2)

## 📓 Notes
- Docs: https://docs.attest.org/docs/developer-tools/eas-sdk
- Optional to use Wagmi hooks (https://docs.attest.org/docs/developer-tools/sdk-wagmi)
