### ISSUE TITLE
Handle Wallet async UI, and tx (attestation) availability.

### ISSUE THREAD

**Issue by ronerlih** [AstralProtocol/astralprotocol#87]
## 💬 Description
On calling "Attest" method, UI should display indication to user throughout the tx lifecycle.
Waiting to sign; processing tx - wait to tx finality and availability on EAS sdk; direct to `astral.global/tx/<tx hash>`.

## 🗞️ Context
EAS MVP.

## 🏗️ TO-DO (tasks or sub-issues)
- [ ] Display tx state with msg/loading spinner, on:
  - [ ] Waiting for user signiture.
  - [ ] waiting for tx-attestation availability.
- [ ] Direct user to `astral.global/tx/<tx hash>`.

## ✅ Acceptance criteria 
- Attestation is available on `astral.global/tx/<tx hash>` when directing user.
- User is given an indication on the async tx lifecycle.

## 📷 Screenshots
![Screen Shot 2024-04-30 at 20 14 44](https://github.com/AstralProtocol/astralprotocol/assets/7093389/c61c1be1-1003-4e07-bdc5-a0d0036a90cb)
