### ISSUE TITLE
On attestation, display map with user's attestation pin.

### ISSUE THREAD

**Issue by ronerlih** [AstralProtocol/astralprotocol#88]
## 💬 Description
On attestation availability, map displays attestation coordinate with a pin.

## 🗞️ Context
EAS MVP.
#80, #87.

## 🏗️ TO-DO (tasks or sub-issues)
- [ ] Read attestation data from EAS api.
- [ ] On attestation availability, map is ~40vh heigh.
- [ ] Map displays attestation coordinate with a pin/marker using the data from EAS api (hash is in the url slug.

## ✅ Acceptance criteria
- On attestation availability, map is minimized.
- Map displays attestation coordinate with a pin/marker

## 📷 Screenshots
![Screen Shot 2024-04-30 at 20 35 17](https://github.com/AstralProtocol/astralprotocol/assets/7093389/2129319e-4619-4195-add4-e1721fdcbbac)
![Screen Shot 2024-04-30 at 20 37 37](https://github.com/AstralProtocol/astralprotocol/assets/7093389/12683153-8455-4519-9361-a236292a9df6)

## 📓 Notes
- EAS SDK https://docs.attest.org/docs/developer-tools/eas-sdk
