### ISSUE TITLE
Add Attestation provider component 

### ISSUE THREAD

**Issue by ronerlih** [AstralProtocol/astralprotocol#89]
## 📘 Story (required for top level issues pls)
As a Conference attendee who checked in, I'd like to view and share my check-in attestation info.

## 💬 Description
Create an attestationProvider component, which is displayed on `astral.global/tx/0x...`. Get attestation info onload, pass data to nested Map and Attestation info components. provide links to ethScan according to chain.

## 🗞️ Context
EAS MVP. 
#88 

## 🏗️ TO-DO (tasks or sub-issues)
- [x] Create an attestationProvider component, which is displayed on `astral.global/tx/0x...`
- [x] Create a nested attestationInfo component to display attestation data.
- [x] Get attestation info onload (EAS SDK).
- [ ] #91

## ✅ Acceptance criteria
- Display attestation info according to url slug.
- Page is public (no need to connect wallet).
- Attestation data is passed to nested Map & AttestationInfo components.
- Add links to relevant chain scanner.

## 📷 Screenshots
![Screen Shot 2024-04-30 at 20 48 42](https://github.com/AstralProtocol/astralprotocol/assets/7093389/4c76ae81-da32-4cf9-8d4e-5953eb4c41c0)
