### ISSUE TITLE
Create pages according to views 

### ISSUE THREAD

**Issue by ronerlih** [AstralProtocol/astralprotocol#90]
## 💬 Description
Create pages according to views as a scaffolding for app navigation
## 🗞️ Context
EAS MVP, [figma board](https://www.figma.com/file/0y3zxXCoTMLKO8cp3Ymf7T/How-Astral-Works-%E2%80%94%C2%A0Flow-Diagram?type=whiteboard&node-id=0-1&t=7hH3GR1PJTaABzJS-0)

## 🏗️ TO-DO (tasks or sub-issues)
- [ ] checkin-form view (page)
- [ ] attestation view (page)
- [x] home (page.tsx) exists - landing page

## ✅ Acceptance criteria
- Three pages components
- Navigation with a next Link component works!
