### ISSUE TITLE
Rename `eas-checkin-dapp` repository to `astral-logbook`

### ISSUE THREAD

**Issue by johnx25bd** [AstralProtocol/astralprotocol#99]
## 📘 Story (required for top level issues pls)

We want branding to be coherent. Rename the repo + relevant content within the app so it aligns with our brand identity for the Logbook product. 

## 💬 Description
Devs should type `git clone git@github.com:AstralProtocol/astral-logbook.git`

## 🏗️ TO-DO (tasks or sub-issues)
- [ ] Rename the git repo
- [ ] Update relevant "remote" urls etc
- [ ] Do our best to update points in the dapp where it refers to the deprecated language
   - "checking in" -> "recording an entry"
   - "check-in" -> "Log entry"
   - etc

## 📓 Notes

There are still some questions about branding so do our best
